# Generated by Django 4.2.5 on 2023-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='reference_id',
            field=models.CharField(default='e74b03d09a8a43449a7cf83883c38bf7', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
