# Generated by Django 4.2.5 on 2023-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_alter_studentdetails_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='reference_id',
            field=models.CharField(default='cc903a1a9d464ce1b79deeec0428cb49', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
