# Generated by Django 4.2.5 on 2023-12-19 14:04

from django.db import migrations, models
import restapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_alter_studentdetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='reference_id',
            field=models.CharField(default=restapp.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
